#https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

[tasks.default]
dependencies = [
    "build",
    "post-build",
]

[tasks.build]
command = "cargo"
args = ["build",]

[tasks.post-build]
linux_alias = "linux_post-build"
windows_alias = "windows_post-build"

[tasks.linux_post-build]
script = [
    "\\cp ~/rustprojects/mem4_game/target/debug/mem4_server -rf -v ~/rustprojects/mem4_game/webfolder",
    # I cannot script the exact IP here.  
    # It must be copied from the mem4_server.exe output.
    "alias chrome=\"/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe\"",
    "chrome http://127.0.0.1:8084", 
    "chrome http://127.0.0.1:8084", 
    "chrome http://127.0.0.1:8084", 
    "cd ../webfolder",
    "sudo ./mem4_server"
]

[tasks.windows_post-build]
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem4_game\\target\\debug\\mem4_server.exe c:\\Users\\Luciano\\rustprojects\\mem4_game\\webfolder\\ /y ",
    # I cannot script the exact IP here.  
    # It must be copied from the mem4_server.exe output.
    "start chrome http://127.0.0.1:8084", 
    "start chrome http://127.0.0.1:8084", 
    "start chrome http://127.0.0.1:8084", 
    "cd ..\\webfolder",
    "mem4_server.exe"
]
