# mem4_game/mem4_server/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build_dev",
        "post_build_dev",
    ]

    [tasks.release]
    description = "cargo build release"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build_release",
        "post_build_release",
    ]

    [tasks.doc]
    description = "call cargo doc"
    clear=true
    dependencies = [
        "insert_readme",
        "cargo_doc",
        "cargo_docs_copy"
    ]

#endregion

#why is task "empty" in the list of public tasks?

[tasks.build_dev]
clear=true
private=true
command = "cargo"
args = ["build"]

[tasks.build_release]
clear=true
private=true
command = "cargo"
args = ["build","--release"]

[tasks.post_build_dev]
clear=true
private=true
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem4_game\\target\\debug\\mem4_server.exe c:\\Users\\Luciano\\rustprojects\\mem4_game\\webfolder\\ /y ",
    # I cannot script the exact IP here.  
    # It must be copied from the mem4_server.exe output.
    "start chrome http://127.0.0.1:8084", 
    "start chrome http://127.0.0.1:8084", 
    "start chrome http://127.0.0.1:8084", 
    "cd ..\\webfolder",
    "mem4_server.exe"
]

[tasks.post_build_release]
clear=true
private=true
script = [
    "\\cp /mnt/c/Users/Luciano/rustprojects/mem4_game/target/release/mem4_server -rf -v /mnt/c/Users/Luciano/rustprojects/mem4_game/webfolder",
    # I cannot script the exact IP here.  
    # It must be copied from the mem4_server.exe output.
    "alias chrome=\"/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe\"",
    "chrome http://127.0.0.1:8084", 
    "chrome http://127.0.0.1:8084", 
    "chrome http://127.0.0.1:8084", 
    "cd ../webfolder",
    "sudo ./mem4_server"
]

[tasks.insert_readme]
description = "copy the content of readme.md into *.rs comments (for the docs)"
clear = true
private = true
script= ["lmake_readme"]

[tasks.cargo_doc]
description = "call cargo doc"
clear = true
private = true
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]

[tasks.cargo_docs_copy]
description = "copy target doc to docs"
clear = true
private = true
script = [
    "\\cp /mnt/c/Users/Luciano/rustprojects/mem4_game/target/doc -rf -v /mnt/c/Users/Luciano/rustprojects/mem4_game/docs",
]

[tasks.lmake_version_from_date]
description = "in cargo.toml change version to today date"
clear = true
private = true
script= ["lmake_version_from_date"]

