# mem4_game/mem4_server/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build-dev",
        "post-build",
    ]

    [tasks.release]
    description = "cargo build release"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build-release",
        "post-build",
    ]

    [tasks.doc]
    description = "call cargo doc"
    clear=true
    dependencies = [
        "insert-readme",
        "cargo-doc",
        "cargo-docs-copy"
    ]

#endregion

#why is task "empty" in the list of public tasks?

[tasks.build-dev]
clear=true
private=true
command = "cargo"
args = ["build"]

[tasks.build-release]
clear=true
private=true
command = "cargo"
args = ["build","--release"]

[tasks.post-build]
clear=true
private=true
linux_alias = "linux_post-build"
windows_alias = "windows_post-build"

[tasks.linux_post-build]
clear=true
private=true
script = [
    "\\cp ~/rustprojects/mem4_game/target/debug/mem4_server -rf -v ~/rustprojects/mem4_game/webfolder",
    # I cannot script the exact IP here.  
    # It must be copied from the mem4_server.exe output.
    "alias chrome=\"/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe\"",
    "chrome http://127.0.0.1:8084", 
    "chrome http://127.0.0.1:8084", 
    "chrome http://127.0.0.1:8084", 
    "cd ../webfolder",
    "sudo ./mem4_server"
]

[tasks.windows_post-build]
clear=true
private=true
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem4_game\\target\\debug\\mem4_server.exe c:\\Users\\Luciano\\rustprojects\\mem4_game\\webfolder\\ /y ",
    # I cannot script the exact IP here.  
    # It must be copied from the mem4_server.exe output.
    "start chrome http://127.0.0.1:8084", 
    "start chrome http://127.0.0.1:8084", 
    "start chrome http://127.0.0.1:8084", 
    "cd ..\\webfolder",
    "mem4_server.exe"
]


[tasks.insert-readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["..\\..\\utils\\lmake_readme.exe"]

[tasks.cargo-doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]

[tasks.cargo-docs-copy]
clear = true
private = true
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem4_game\\target\\doc\\*.* c:\\Users\\Luciano\\rustprojects\\mem4_game\\docs\\ /e /i /y /s ",
]

[tasks.lmake_version_from_date]
clear = true
private = true
description = "in cargo.toml change version to today date"
script= ["..\\..\\utils\\lmake_version_from_date.exe"]

