# mem4_game/mem4/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
        "build-dev",
        "post-build",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
        "build-release",
        "post-build",
    ]

    [tasks.doc]
    description = "call cargo doc"
    clear=true
    dependencies = [
        "insert-readme",
        "cargo-doc",
    ]

# endregion

[tasks.build-dev]
clear = true
private = true
command = "wasm-pack"
args = ["build", "--target", "web","--dev"]

[tasks.build-release]
clear = true
private = true
command = "wasm-pack"
args = ["build","--target", "web","--release"]

[tasks.post-build]
clear = true
private = true
linux_alias = "linux_post-build"
windows_alias = "windows_post-build"

[tasks.linux_post-build]
clear = true
private = true
script = [
    "\\cp ~/rustprojects/mem4_game/mem4/pkg/* -rf -v ~/rustprojects/mem4_game/webfolder/mem4/pkg",
]

[tasks.windows_post-build]
clear = true
private = true
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem4_game\\mem4\\pkg\\*.* c:\\Users\\Luciano\\rustprojects\\mem4_game\\webfolder\\mem4\\pkg\\ /e /i /y /s ",
]


[tasks.insert-readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["..\\..\\utils\\lmake_readme.exe"]

[tasks.cargo-doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]
